### ISSUE TITLE
1.17.1 Fabric Branch

### ISSUE THREAD

**Issue by AzureDoom** [mactso/ExperienceBugFix#1]
Hi I have forked and created a 1.17.1 branch I'd like to PR which also involves a formatting clean up to match your forge layout, would you be able to create a `fabric_1.17` branch for the PR so it doesn't overwrite any existing branches?

**Comment by mactso** [comment]
Hi I'm sorry I didn't see this!
yes I will create the branch.

**Comment by mactso** [comment]
Okay the branch is created.   I was sick for the last week and lupicus was sick before that so I got distracted.
I get messages on the discord more reliably, FYI.

**Comment by AzureDoom** [comment]
Alright, thanks! PR sent. I did try to find your discord but had no luck.

**Comment by mactso** [comment]
/There should be an invite link to discord in all our mods.  if there isn't one in FixExperienceBug then I will add one

**Comment by mactso** [comment]
Here is the invite link pending me updating the page.

https://discord.gg/fmdRFmmvBj

**Comment by mactso** [comment]
I'm testing this in a production environment now- should be up within the hour.
