### ISSUE TITLE
Curseforge download issue

### ISSUE THREAD

**Issue by DDriggs00** [mactso/ExperienceBugFix#3]
Something is preventing this mod from being downloaded as a part of a modpack on third-party launchers. This is typically caused by a misconfigured setting in Curseforge.

**Comment by mactso** [comment]
Hi, the mods remain available for free to build from Github and you can pass them to your friends manually.

We have the option for users to support our mods for altloaders on Patreon.

If you choose to support a mod, you'll get credit as mod supporter on the curseforge page (if you want it but if you want to remain anonymous that is cool too!).

I'm slowing working the patreon buttons around the mods.  It's currently on regrowth, save your pets, harder farther, and I think fix experience bug.   Entering from those buttons doesn't choose a particular mod.  You do that by posting which mod you want to support.

Cheers,
Two Guys,
MacTso

**Comment by DDriggs00** [comment]
I'm unsure what all that has to do with blocking Non-Curseforge Launchers.

**Comment by DDriggs00** [comment]
Also, Here's a more detailed appeal written by someone with a bit more experience than me: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

**Comment by mactso** [comment]
> m unsure what all that has to do with blocking Non-Curseforge Launchers.

A large number of alternative loaders have arisen who sell advertising but keep all the revenue and don't pay any of the storage or bandwidth costs.  We also don't get credit for any downloads.

We provide the software free to anyone who wants to build it from Github.  We have a patreon model for people who want to support particular mods and make them available on all alternative modloaders. 

It looks like 6 of our mods will be supported by the community by August.

Hope this helps.
Two Guys,
MacTso
