### ISSUE TITLE
[1.19.2 Forge] Server crashes on startup, mod isn't detecting forge or something

### ISSUE THREAD

**Issue by BugmanBugman** [mactso/ExperienceBugFix#5]
https://gist.github.com/BugmanBugman/09c70c3b04ca459e87a51ab5d3a059f1

**Comment by mactso** [comment]
Hi ... just seeing this after thanks giving.  Which mod is having this issue?  I can't see from the log.  I'll try to get it fixed asap once i know.

Thanks!

**Comment by mactso** [comment]
Oh wait- I see.  ExperienceBugFix.  
I'll get on it.

**Comment by mactso** [comment]
Okay, this has already been fixed.  I think someone (maybe you) put in a bug report about it on discord or curseforge before the holidays.

Sorry for the delay via the github issue channel.  Rough Holidays.

With Best Regards,
Two Guys,
MacTso

**Comment by BugmanBugman** [comment]
Appreciate it man, no worries. Hope you had a good holiday

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aking4125** [comment]
Actually, it truly doesn't load on the server. It's not detecting any Forge version at all in 1.19.2
[crash-2022-12-11_14.11.50-fml.txt](https://github.com/mactso/ExperienceBugFix/files/10203032/crash-2022-12-11_14.11.50-fml.txt)

Removing this mod allows the server to continue. Any ideas? The client works fine.

**Comment by evelynhathaway** [comment]
@aking4125 I was able to open the `ExperienceBugFix-1.19-1.41.2.2.jar` file in 7zip and edit `META-INF/mods.toml` to match the one line changed in #7 and it worked. It's a workaround until a new patch is released.

**Comment by mactso** [comment]
Thank you.  I'll fix this (and test it in 1.19.3 as well).

I've been focused SBU and missed this.
